#!/usr/bin/env python
"""haiku_prep.py — end-of-tick prep work.

Three jobs, each failure-safe (one breaking doesn't block the others):

  1. validate_specs        — pure Python; catch + auto-fix common spec bugs
                              (value:→min:, missing query_kind on cypher_analysis)
  2. precache_research     — pure Python; pre-fetch next N URLs from the
                              research queue to data/research_cache/, so the
                              next RESEARCH tick reads from disk instead of
                              issuing a live WebFetch
  3. preclassify_proposals — Haiku via Anthropic API; annotate each pending
                              proposal in data/proposed_tasks.yaml with
                              {classification, duplicate_of, relates_to,
                               note} so the next IMPL tick's proposal-review
                              becomes a confirm rather than a discover

Called by scripts/tick_finalize.py after the main tick work but before the
orchestrator's commit step, so all artefacts land in the same tick commit.

Idempotent. Safe to run multiple times — none of the jobs duplicate work.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

try:
    import yaml
    import requests
except ImportError as e:
    print(f"[haiku_prep] missing dependency: {e} — skipping", file=sys.stderr)
    sys.exit(0)

ROOT = Path(__file__).resolve().parent.parent
RESEARCH_CACHE = ROOT / "data" / "research_cache"
PROPOSED_PATH = ROOT / "data" / "proposed_tasks.yaml"
BACKLOG_PATH = ROOT / "ralph_backlog.yaml"
QUEUE_PATH = ROOT / "data" / "research_neo4j_crawl" / "neo4j_research_queue.yaml"
STATE_PATH = ROOT / "ralph_state.json"
WARN_PATH = ROOT / "data" / "spec_warnings.md"

# Anthropic API config
HAIKU_MODEL = os.getenv("HAIKU_PREP_MODEL", "claude-haiku-4-5")
HAIKU_TIMEOUT = 30
HAIKU_MAX_TOKENS = 1500
PRECACHE_N = int(os.getenv("HAIKU_PREP_PRECACHE_N", "2"))
PRECACHE_TTL_HOURS = 24


def load_env():
    """Load .env into os.environ. Uses python-dotenv (same as the rest of
    the project) so .env overrides empty shell vars."""
    env_path = ROOT / ".env"
    if not env_path.exists():
        return
    try:
        from dotenv import load_dotenv
        load_dotenv(env_path, override=True)
    except ImportError:
        # Fallback: hand-roll, treating .env as source of truth
        for line in env_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and "=" in line and not line.startswith("#"):
                k, v = line.split("=", 1)
                v = v.strip()
                if v:
                    os.environ[k.strip()] = v


# ── Job 1: spec validator ─────────────────────────────────────────────────────

def validate_specs():
    """Audit ralph_backlog.yaml. Auto-fix safe patterns; warn for the rest."""
    if not BACKLOG_PATH.exists():
        return
    txt = BACKLOG_PATH.read_text(encoding="utf-8")
    warnings = []

    # Auto-fix 1: file_min_bytes: { ..., value: N } → min: N
    new_txt, n_value = re.subn(
        r"(file_min_bytes:\s*\{[^}]*?,\s*)value(:\s*\d+\s*\})",
        r"\1min\2",
        txt,
    )
    if n_value:
        warnings.append(
            f"auto-fix: rewrote {n_value} `value:` → `min:` in file_min_bytes blocks"
        )
        BACKLOG_PATH.write_text(new_txt, encoding="utf-8")
        txt = new_txt

    # Check 2: pending cypher_analysis tasks missing query/script/query_kind=manual
    state = {}
    if STATE_PATH.exists():
        try:
            state = json.loads(STATE_PATH.read_text(encoding="utf-8"))
        except Exception:
            pass
    done = set(state.get("done_task_ids", [])) | set(
        state.get("quarantined_task_ids", [])
    )
    try:
        b = yaml.safe_load(txt) or {}
        for t in b.get("tasks", []) or []:
            if t.get("id") in done:
                continue
            if t.get("type") != "cypher_analysis":
                continue
            spec = t.get("spec") or {}
            if (
                "query" not in spec
                and "script" not in spec
                and spec.get("query_kind") != "manual"
            ):
                warnings.append(
                    f"WARN `{t['id']}` (cypher_analysis, p{t.get('priority', 0)}): "
                    f"no query/script/query_kind=manual — will run in manual mode."
                )
    except Exception as e:
        warnings.append(f"spec audit parse error: {e}")

    if warnings:
        out = [
            f"# Spec warnings — {datetime.now(timezone.utc).isoformat()}",
            "",
            "_Auto-generated by `scripts/haiku_prep.py`._",
            "",
        ]
        out.extend(f"- {w}" for w in warnings)
        WARN_PATH.write_text("\n".join(out) + "\n", encoding="utf-8")
    elif WARN_PATH.exists():
        WARN_PATH.unlink()


# ── Job 2: research URL pre-cache ─────────────────────────────────────────────

def precache_research():
    """Pre-fetch the next N WebFetch-handler URLs. YT-handler items skipped
    (different code path, 429-rate-limited anyway)."""
    if not QUEUE_PATH.exists():
        return
    RESEARCH_CACHE.mkdir(parents=True, exist_ok=True)

    try:
        q = yaml.safe_load(QUEUE_PATH.read_text(encoding="utf-8")) or {}
    except Exception as e:
        print(f"[haiku_prep] precache queue read failed: {e}", file=sys.stderr)
        return

    # Walk sources in priority order
    sources = []
    for name, src in q.items():
        if not isinstance(src, dict):
            continue
        if src.get("handler", "") == "yt-transcript-skill":
            continue
        items = src.get("queue") or []
        if items:
            sources.append((src.get("source_priority", 0), name, items))
    sources.sort(key=lambda r: -r[0])

    candidates: list[tuple[str, str]] = []
    for _, name, items in sources:
        for item in items:
            if not isinstance(item, dict):
                continue
            url = item.get("url")
            if url:
                candidates.append((url, name))
                if len(candidates) >= PRECACHE_N:
                    break
        if len(candidates) >= PRECACHE_N:
            break

    cutoff = datetime.now(timezone.utc) - timedelta(hours=PRECACHE_TTL_HOURS)
    fetched = 0
    for url, src in candidates:
        slug = hashlib.md5(url.encode()).hexdigest()[:12]
        cache_path = RESEARCH_CACHE / f"{slug}.html"
        meta_path = RESEARCH_CACHE / f"{slug}.meta.json"
        if cache_path.exists():
            try:
                mtime = datetime.fromtimestamp(
                    cache_path.stat().st_mtime, tz=timezone.utc
                )
                if mtime > cutoff:
                    continue
            except Exception:
                pass
        try:
            r = requests.get(
                url,
                timeout=15,
                headers={
                    "User-Agent": "QKG-cache/1.0 (research preload)",
                    "Accept": "text/html,application/xhtml+xml",
                },
            )
            r.raise_for_status()
            # Cap at 200KB to avoid bloating the repo with huge pages
            cache_path.write_text(r.text[:200_000], encoding="utf-8")
            meta_path.write_text(
                json.dumps(
                    {
                        "url": url,
                        "source": src,
                        "fetched_at": datetime.now(timezone.utc).isoformat(),
                        "size_bytes": min(len(r.text), 200_000),
                        "truncated": len(r.text) > 200_000,
                    },
                    indent=2,
                ),
                encoding="utf-8",
            )
            fetched += 1
        except Exception as e:
            print(f"[haiku_prep] precache failed {url}: {e}", file=sys.stderr)

    if fetched:
        print(f"  precache: fetched {fetched}/{len(candidates)} URLs")


# ── Job 3: Haiku pre-classify proposals ───────────────────────────────────────

def preclassify_proposals():
    """For each pending proposal lacking `haiku_notes`, ask Haiku to
    classify and identify backlog overlap. Writes annotations back."""
    if not PROPOSED_PATH.exists() or not BACKLOG_PATH.exists():
        return
    api_key = os.getenv("ANTHROPIC_API_KEY", "").strip()
    if not api_key:
        print("  preclassify: ANTHROPIC_API_KEY not set — skipping")
        return

    try:
        proposed = yaml.safe_load(PROPOSED_PATH.read_text(encoding="utf-8")) or {}
        backlog = yaml.safe_load(BACKLOG_PATH.read_text(encoding="utf-8")) or {}
    except Exception as e:
        print(f"[haiku_prep] preclassify yaml load: {e}", file=sys.stderr)
        return

    pending = proposed.get("pending") or []
    if not pending:
        return

    state = {}
    if STATE_PATH.exists():
        try:
            state = json.loads(STATE_PATH.read_text(encoding="utf-8"))
        except Exception:
            pass
    done = set(state.get("done_task_ids", [])) | set(
        state.get("quarantined_task_ids", [])
    )
    existing = [
        (t["id"], (t.get("description") or "")[:160])
        for t in backlog.get("tasks", []) or []
        if t.get("id") and t["id"] not in done
    ]

    to_annotate = [
        (i, p)
        for i, p in enumerate(pending)
        if isinstance(p, dict) and "haiku_notes" not in p
    ]
    if not to_annotate:
        print("  preclassify: nothing new to annotate")
        return

    # Build prompt (cap existing-task context to keep tokens low)
    lines = [
        "You are a triage assistant for the QKG ralph loop. For each proposed task, "
        "classify it and identify backlog overlap. Be terse. Output STRICT JSON only.",
        "",
        f"# Existing pending backlog tasks ({len(existing)} shown; id + description):",
        "",
    ]
    for tid, desc in existing[:80]:
        lines.append(f"- `{tid}`: {desc}")
    lines.append("")
    lines.append(f"# Proposals to classify ({len(to_annotate)}):")
    lines.append("")
    for i, p in to_annotate:
        task = p.get("task", {}) if isinstance(p, dict) else {}
        lines.append(f"## Proposal {i}: `{task.get('id', '?')}`")
        lines.append(
            f"Type: {task.get('type', '?')}, priority {task.get('priority', '?')}"
        )
        desc = (task.get("description") or "")[:300]
        lines.append(f"Description: {desc}")
        lines.append("")

    lines.append(
        'Output JSON array. Schema per element: '
        '{"index": <int>, "classification": '
        '"actionable" | "duplicate" | "maybe_subsumed" | "obvious_reject", '
        '"duplicate_of": "<existing-task-id or null>", '
        '"relates_to": ["<id>", ...], '
        '"note": "<reasoning, <=120 chars>"}. '
        "Order: same order as the proposals above."
    )

    try:
        resp = requests.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json={
                "model": HAIKU_MODEL,
                "max_tokens": HAIKU_MAX_TOKENS,
                "messages": [{"role": "user", "content": "\n".join(lines)}],
            },
            timeout=HAIKU_TIMEOUT,
        )
        resp.raise_for_status()
        body = resp.json()
        text = body["content"][0]["text"]
        m = re.search(r"\[.*\]", text, re.DOTALL)
        if not m:
            print(f"[haiku_prep] preclassify: no JSON found in response", file=sys.stderr)
            return
        annotations = json.loads(m.group(0))
    except Exception as e:
        print(f"[haiku_prep] preclassify Haiku call failed: {e}", file=sys.stderr)
        return

    n_applied = 0
    for ann in annotations:
        if not isinstance(ann, dict):
            continue
        idx = ann.get("index")
        if idx is None or not isinstance(idx, int) or idx >= len(pending):
            continue
        if not isinstance(pending[idx], dict):
            continue
        pending[idx]["haiku_notes"] = {
            "classification": ann.get("classification"),
            "duplicate_of": ann.get("duplicate_of"),
            "relates_to": ann.get("relates_to", []),
            "note": (ann.get("note") or "")[:200],
            "annotated_at": datetime.now(timezone.utc).isoformat(),
            "model": HAIKU_MODEL,
        }
        n_applied += 1

    if n_applied:
        proposed["pending"] = pending
        PROPOSED_PATH.write_text(
            yaml.safe_dump(proposed, sort_keys=False, allow_unicode=True, width=120),
            encoding="utf-8",
        )
        print(f"  preclassify: annotated {n_applied} proposals")


# ── main ──────────────────────────────────────────────────────────────────────

def main():
    load_env()
    ts = datetime.now(timezone.utc).isoformat()
    print(f"[haiku_prep] starting at {ts}")
    for fn in (validate_specs, precache_research, preclassify_proposals):
        try:
            fn()
            print(f"  [haiku_prep] {fn.__name__} ok")
        except Exception as e:
            print(f"  [haiku_prep] {fn.__name__} FAILED: {e}", file=sys.stderr)
    print(f"[haiku_prep] done")


if __name__ == "__main__":
    main()
