#!/usr/bin/env python
"""
state_snapshot.py — produces STATE_SNAPSHOT.md (auto-rolled "what does QKG look like NOW").

Run by cron orchestrator at the end of each tick (or every N ticks). Also safe to
run by hand. The output replaces the previous STATE_SNAPSHOT.md so it's always a
fresh single-page view.

Idempotent — running twice in a row produces the same file modulo timestamp.
"""
from __future__ import annotations

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError:
    print("install pyyaml first: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "STATE_SNAPSHOT.md"

NOW = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def load_state() -> dict:
    p = ROOT / "ralph_state.json"
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else {}


def load_yaml(path: Path) -> dict:
    if not path.exists():
        return {}
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def git_log(n: int = 15) -> str:
    try:
        out = subprocess.check_output(
            ["git", "log", "--oneline", "-n", str(n)],
            cwd=str(ROOT),
            stderr=subprocess.DEVNULL,
        ).decode("utf-8", errors="replace")
        return out.strip()
    except Exception:
        return "(git log unavailable)"


def git_status_short() -> str:
    try:
        out = subprocess.check_output(
            ["git", "status", "--short"],
            cwd=str(ROOT),
            stderr=subprocess.DEVNULL,
        ).decode("utf-8", errors="replace")
        return out.strip() or "(clean)"
    except Exception:
        return "(git status unavailable)"


def cron_status() -> str:
    """We can't query CronList from a script, but we can detect the marker file."""
    if (ROOT / "data" / "RALPH_STOP").exists():
        return "**HALTED** (data/RALPH_STOP exists)"
    return "(check CronList in active session for live job IDs)"


def render() -> str:
    state = load_state()
    backlog = load_yaml(ROOT / "ralph_backlog.yaml")
    research = load_yaml(ROOT / "data" / "research_backlog.yaml")
    queue = load_yaml(ROOT / "data" / "research_neo4j_crawl" / "neo4j_research_queue.yaml")

    done = set(state.get("done_task_ids", []))
    quar = set(state.get("quarantined_task_ids", []))
    tasks = backlog.get("tasks", []) or []
    pending = [t for t in tasks if t["id"] not in done and t["id"] not in quar]
    pending.sort(key=lambda t: -int(t.get("priority", 0)))

    research_topics = research.get("topics", []) or []
    open_topics = [t for t in research_topics if t.get("status") == "open"]
    open_topics.sort(key=lambda t: -int(t.get("priority", 0)))

    # Multi-source research queue counts
    queue_summary = []
    for src_name, src in (queue or {}).items():
        if not isinstance(src, dict):
            continue
        if src_name in {"version", "fetched_at", "description"}:
            continue
        if "queue" in src:
            queue_summary.append((src_name, len(src.get("queue") or []),
                                   int(src.get("source_priority", 0))))
        elif "estimated_remaining" in src:
            queue_summary.append((src_name, int(src.get("estimated_remaining", 0)),
                                   int(src.get("source_priority", 0))))
    queue_summary.sort(key=lambda r: -r[2])

    api = state.get("api_usage", {}) or {}
    win_24h_calls = sum(int(r[1]) for r in (api.get("window") or []))

    history = state.get("history") or []
    recent_ticks = history[-10:][::-1]

    out = []
    out.append(f"# STATE_SNAPSHOT — {NOW}")
    out.append("")
    out.append("Auto-generated by `scripts/state_snapshot.py`. Overwritten on each run.")
    out.append("Read this first when picking up context. Pair with `SESSION_LOG.md` and the most recent note in `QKG Obsidian/sessions/`.")
    out.append("")

    # ── Loop status ──────────────────────────────────────────────────────
    out.append("## Loop status")
    out.append("")
    out.append(f"- **Tick count:** {state.get('tick_count', 0)}")
    out.append(f"- **Last tick:** {state.get('last_tick', '(none)')}")
    out.append(f"- **In progress:** {state.get('in_progress') or '(idle)'}")
    out.append(f"- **24h API calls:** {win_24h_calls}")
    out.append(f"- **Cron job:** {cron_status()}")
    out.append("")

    # ── Backlogs ─────────────────────────────────────────────────────────
    out.append("## Backlog health")
    out.append("")
    out.append(f"- **ralph_backlog:** {len(tasks)} total · {len(done)} done · {len(quar)} quarantined · {len(pending)} pending")
    out.append(f"- **research_backlog:** {len(research_topics)} topics · {len(open_topics)} open")
    if queue_summary:
        out.append("- **Multi-source research queue (`neo4j_research_queue.yaml`):**")
        for name, n, prio in queue_summary:
            out.append(f"   - `{name}` (priority {prio}): {n} item(s)")
    out.append("")

    # ── Top pending ralph tasks ──────────────────────────────────────────
    out.append("## Top 8 pending ralph tasks (by priority)")
    out.append("")
    out.append("| pri | id | type |")
    out.append("|----:|------|------|")
    for t in pending[:8]:
        out.append(f"| {t.get('priority', 0)} | `{t['id']}` | {t.get('type', '?')} |")
    out.append("")

    # ── Top open research topics ─────────────────────────────────────────
    out.append("## Top 6 open research topics")
    out.append("")
    out.append("| pri | id | tags |")
    out.append("|----:|------|------|")
    for t in open_topics[:6]:
        tags = ", ".join(t.get("tags", []) or [])
        out.append(f"| {t.get('priority', 0)} | `{t['id']}` | {tags} |")
    out.append("")

    # ── Recent ticks ─────────────────────────────────────────────────────
    out.append("## Last 10 ticks")
    out.append("")
    out.append("| ts | task | status | notes |")
    out.append("|----|------|--------|-------|")
    for h in recent_ticks:
        ts = (h.get("finished_at") or h.get("started_at") or "")[:16]
        notes = (h.get("notes") or "").replace("\n", " ").replace("|", "/")[:80]
        out.append(f"| {ts} | `{h.get('task_id','')}` | {h.get('status','')} | {notes} |")
    out.append("")

    # ── Recent commits ───────────────────────────────────────────────────
    out.append("## Last 15 commits")
    out.append("")
    out.append("```")
    out.append(git_log(15))
    out.append("```")
    out.append("")

    # ── Working tree status ──────────────────────────────────────────────
    out.append("## Working tree")
    out.append("")
    out.append("```")
    out.append(git_status_short())
    out.append("```")
    out.append("")

    # ── Where to look next ───────────────────────────────────────────────
    out.append("## What to look at next (heuristic)")
    out.append("")
    out.append("- `SESSION_LOG.md` (top entry) — last operator's hand-off")
    out.append("- `QKG Obsidian/sessions/` (newest file) — most recent session reflection")
    out.append("- `data/research_neo4j_crawl/INDEX.md` — research crawl entry point")
    out.append("- `ralph_log.md` Codebase Patterns block — durable lessons")
    out.append("- `CLAUDE_INDEX.md` — lean project index (replaces full CLAUDE.md as loop context)")
    out.append("")
    out.append(f"_Generated by `scripts/state_snapshot.py` at {NOW}_")
    out.append("")

    return "\n".join(out)


def render_status_mobile() -> str:
    """Phone-friendly top-of-repo status. Short. Links use GitHub-compatible
    relative paths so taps from the GitHub mobile app / Dispatch jump to the
    right file."""
    state = load_state()
    backlog = load_yaml(ROOT / "ralph_backlog.yaml")
    research = load_yaml(ROOT / "data" / "research_backlog.yaml")
    queue = load_yaml(ROOT / "data" / "research_neo4j_crawl" / "neo4j_research_queue.yaml")

    done = set(state.get("done_task_ids", []))
    quar = set(state.get("quarantined_task_ids", []))
    tasks = backlog.get("tasks", []) or []
    pending = [t for t in tasks if t["id"] not in done and t["id"] not in quar]
    pending.sort(key=lambda t: -int(t.get("priority", 0)))

    open_topics = sum(
        1 for t in (research.get("topics", []) or []) if t.get("status") == "open"
    )

    queue_total = 0
    for src in (queue or {}).values():
        if isinstance(src, dict) and "queue" in src:
            queue_total += len(src.get("queue") or [])

    api = state.get("api_usage", {}) or {}
    win = api.get("window") or []
    calls_24h = sum(int(r[1]) for r in win)

    history = state.get("history") or []
    recent = history[-5:][::-1]

    out = []
    out.append("# QKG — Status")
    out.append("")
    out.append(f"_Updated {NOW} — auto by `scripts/state_snapshot.py`_")
    out.append("")
    out.append("## Loop")
    out.append(f"- Tick **{state.get('tick_count', 0)}** | last `{state.get('last_tick','(none)')[:16]}`")
    out.append(f"- In progress: **{state.get('in_progress') or '_idle_'}**")
    out.append(f"- 24h API calls: {calls_24h}")
    out.append("")

    out.append("## Last 5 ticks")
    out.append("")
    for h in recent:
        ts = (h.get("finished_at") or h.get("started_at") or "")[:16]
        st = h.get("status", "")
        emoji = {"DONE": "✓", "DONE_WITH_CONCERNS": "⚠", "FAILED": "✗",
                 "QUARANTINED": "🚫", "SKIPPED": "·", "BLOCKED": "⛔",
                 "REGRESSION": "↓", "NEEDS_CONTEXT": "?"}.get(st, "•")
        out.append(f"- {emoji} `{h.get('task_id', '')}` ({st}, {ts})")
    out.append("")

    out.append("## Recent commits")
    out.append("")
    out.append("```")
    out.append(git_log(8))
    out.append("```")
    out.append("")

    out.append("## Top 5 pending tasks")
    out.append("")
    for t in pending[:5]:
        flag = ""
        d = (t.get("description") or "").lower()
        if "[opus]" in d:
            flag = " 🧠"
        if "[answer-quality]" in d:
            flag += " ⭐"
        out.append(
            f"- **{t.get('priority', 0)}** `{t['id']}` ({t.get('type', '')}){flag}"
        )
    out.append("")

    out.append("## Backlog health")
    out.append("")
    out.append(
        f"- **{len(pending)}** pending • **{len(done)}** done • **{len(quar)}** quarantined"
    )
    out.append(f"- Research queue: **{queue_total}** items across {len([s for s in (queue or {}).values() if isinstance(s, dict)])} sources")
    out.append(f"- Open research topics: **{open_topics}**")
    out.append("")

    out.append("## Files worth opening")
    out.append("")
    out.append("- [📊 MORNING_REPORT.md](MORNING_REPORT.md) — refreshed every 6 ticks")
    out.append("- [📋 STATE_SNAPSHOT.md](STATE_SNAPSHOT.md) — full detail view")
    out.append("- [📝 SESSION_LOG.md](SESSION_LOG.md) — operator hand-offs between sessions")
    out.append("- [📚 ralph_backlog.yaml](ralph_backlog.yaml) — task queue")
    out.append("- [📥 data/proposed_tasks.yaml](data/proposed_tasks.yaml) — pending review (Haiku pre-annotated)")
    out.append("- [🧠 data/sonnet_drafts/](data/sonnet_drafts/) — Opus pre-warmed plans")
    out.append("- [🗒️ QKG Obsidian/](QKG%20Obsidian/) — knowledge vault (MOC.md entry)")
    out.append("")
    out.append(f"_Tap any link to open in GitHub. Use the file watcher on your phone for live updates._")
    out.append("")
    return "\n".join(out)


def main():
    snapshot_text = render()
    OUT.write_text(snapshot_text, encoding="utf-8")
    # Mirror full snapshot into the vault as CURRENT STATE.md
    vault = ROOT / "QKG Obsidian" / "CURRENT STATE.md"
    if vault.parent.exists():
        vault.write_text(snapshot_text, encoding="utf-8")
    # Also write a phone-friendly STATUS.md at repo root for GitHub-mobile / Dispatch
    status_text = render_status_mobile()
    (ROOT / "STATUS.md").write_text(status_text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} and STATUS.md")


if __name__ == "__main__":
    main()
