#!/usr/bin/env python
"""
tick_finalize.py — single end-of-tick housekeeping entry point.

Called by the cron orchestrator's subagent at the end of every tick. Runs:
  1. state_snapshot.py — overwrites STATE_SNAPSHOT.md (and mirrors to vault CURRENT STATE.md)
  2. vault_update.py — appends today's commits to daily note, creates research stubs
  3. MORNING_REPORT.md — generated/updated every 12 ticks

Idempotent. Safe to re-run.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCRIPTS = ROOT / "scripts"

NOW = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def run(script: str) -> bool:
    p = SCRIPTS / script
    if not p.exists():
        print(f"  [tick_finalize] {script} not found, skipping")
        return False
    try:
        out = subprocess.check_output(
            [sys.executable, str(p)], cwd=str(ROOT), stderr=subprocess.STDOUT
        ).decode("utf-8", errors="replace").strip()
        print(f"  [tick_finalize] {script}: {out}")
        return True
    except subprocess.CalledProcessError as e:
        print(f"  [tick_finalize] {script} FAILED: {e.output.decode('utf-8', errors='replace')[:300]}")
        return False


def maybe_morning_report():
    """Generate/update MORNING_REPORT.md if tick_count % 12 == 0."""
    state_path = ROOT / "ralph_state.json"
    if not state_path.exists():
        return
    try:
        state = json.loads(state_path.read_text(encoding="utf-8"))
    except Exception:
        return
    tc = int(state.get("tick_count", 0))
    if tc == 0 or tc % 12 != 0:
        return

    # Pull data
    history = state.get("history", []) or []
    last_12 = history[-12:]
    done = state.get("done_task_ids", []) or []
    quar = state.get("quarantined_task_ids", []) or []

    out = []
    out.append(f"# MORNING_REPORT — tick {tc}")
    out.append("")
    out.append(f"_Auto-generated by `scripts/tick_finalize.py` at {NOW}._")
    out.append(f"_Triggered every 12 ticks. Refreshed each cycle._")
    out.append("")

    out.append("## Last 12 ticks")
    out.append("")
    out.append("| ts | task | type | status | notes |")
    out.append("|----|------|------|--------|-------|")
    for h in last_12:
        ts = (h.get("finished_at") or h.get("started_at") or "")[:16]
        notes = (h.get("notes") or "").replace("\n", " ").replace("|", "/")[:90]
        out.append(f"| {ts} | `{h.get('task_id','')}` | {h.get('type','')} | {h.get('status','')} | {notes} |")
    out.append("")

    # Highlight completions vs failures in this window
    statuses = [h.get("status", "") for h in last_12]
    n_done = sum(1 for s in statuses if s in {"DONE", "DONE_WITH_CONCERNS"})
    n_failed = sum(1 for s in statuses if s in {"FAILED", "REGRESSION", "BLOCKED"})

    out.append(f"## Window summary")
    out.append("")
    out.append(f"- {n_done} successful, {n_failed} failed, {len(last_12) - n_done - n_failed} other")
    out.append(f"- All-time: {len(done)} done, {len(quar)} quarantined")
    out.append("")
    out.append(f"## Cumulative tick count: {tc}")
    out.append("")
    out.append(f"## Next pickups")
    out.append("")
    out.append(f"_See STATE_SNAPSHOT.md for the live top-pending list._")
    out.append("")

    (ROOT / "MORNING_REPORT.md").write_text("\n".join(out), encoding="utf-8")
    # Mirror to vault if it exists
    vault_copy = ROOT / "QKG Obsidian" / "MORNING REPORT.md"
    if vault_copy.parent.exists():
        vault_copy.write_text("\n".join(out), encoding="utf-8")
    print(f"  [tick_finalize] MORNING_REPORT.md refreshed (tick {tc})")


def main():
    print(f"[tick_finalize] starting at {NOW}")
    run("state_snapshot.py")
    run("vault_update.py")
    # Haiku-driven prep work — failure-safe, output rides in same tick commit.
    # Set HAIKU_PREP_DISABLED=1 to skip (e.g. for offline runs).
    if os.environ.get("HAIKU_PREP_DISABLED") != "1":
        run("haiku_prep.py")
    maybe_morning_report()
    print(f"[tick_finalize] done")


if __name__ == "__main__":
    main()
